In [1]:
import numpy as np 

In [3]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr%2!=0]=-1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [11]:
a = np.array([1, 2, 3, 4, 5, 6])
a1 = a.reshape(2, -1)
print(a1)

[[1 2 3]
 [4 5 6]]


In [13]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
c = np.concatenate((a,b), axis=0)
print(c)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [14]:
a = np.array([1,2,3])
a1 = np.repeat(a, 3)
a2 = np.tile(a, 3)
arr = np.concatenate((a1,a2))
print(arr)

[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


In [17]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
arr_common = np.intersect1d(a, b)
arr = a[np.isin(a, b)]
print(arr)
print(arr_common) 

[2 2 4 4]
[2 4]


In [23]:
np.random.seed(100)
a = np.random.uniform(1,50, 20)
print(a)
max_5 = np.argsort(a)[-5:][::-1]
print(max_5)

[27.62684215 14.64009987 21.80136195 42.39403048  1.23122395  6.95688692
 33.86670515 41.466785    7.69862289 29.17957314 44.67477576 11.25090398
 10.08108276  6.31046763 11.76517714 48.95256545 40.77247431  9.42510962
 40.99501269 14.42961361]
[15 10  3  7 18]


In [28]:
a3=np.array([1,2,3,np.nan,5,6,7,np.nan])
arr = a3[~np.isnan(a3)]
print(arr)

[1. 2. 3. 5. 6. 7.]


In [29]:
a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8])

arr = np.linalg.norm(b-a)
print(arr)

6.708203932499369


In [33]:
x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])
indices = np.where(x==1)[0]
result = indices[5]
print(result)

10


In [34]:
np.random.seed(100)
a = np.random.randint(0, 5, 10)
print(a)
_, counts = np.unique(a, return_counts=True) 
repeated = np.where(counts > 1)[0]
result = np.zeros(a.shape, dtype=bool)
for value in repeated: 
    indices = np.where(a == value)[0]
    result[indices[1:]]=True
print(result)

[0 0 3 0 2 4 2 2 2 2]
[False  True False  True False False False False False False]
