In [1]:
import numpy as np 

In [3]:
# Task 1 
a = np.arange(1,11)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [4]:
m = np.zeros((3,3), dtype=int)
print(m)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [5]:
m = np.random.randint(1, 11,(5,5))
print(m)

[[ 8  2  1  5 10]
 [ 4 10  9  7 10]
 [ 1 10  1  3  5]
 [ 4  8  3  5  4]
 [ 6  1  3  8 10]]


In [6]:
m = np.random.random((4,4))
print(m)

[[0.12726661 0.17503046 0.03861119 0.72375266]
 [0.86504903 0.83437229 0.61299369 0.06801569]
 [0.10281106 0.95567564 0.32681945 0.468759  ]
 [0.2450635  0.95213277 0.30234681 0.68650013]]


In [8]:
m = np.random.randint(1, 11,(5,5))
a = m + 10
b = m - 5
c = m * 15
print(m)
print(a)
print(b)
print(c)

[[ 1  1  5  8  9]
 [ 1  1  9  4  5]
 [ 8  3  3  1  8]
 [10  2  1  3  4]
 [10  6  2  7  2]]
[[11 11 15 18 19]
 [11 11 19 14 15]
 [18 13 13 11 18]
 [20 12 11 13 14]
 [20 16 12 17 12]]
[[-4 -4  0  3  4]
 [-4 -4  4 -1  0]
 [ 3 -2 -2 -4  3]
 [ 5 -3 -4 -2 -1]
 [ 5  1 -3  2 -3]]
[[ 15  15  75 120 135]
 [ 15  15 135  60  75]
 [120  45  45  15 120]
 [150  30  15  45  60]
 [150  90  30 105  30]]


In [10]:
a = np.arange(7)
b = np.random.randint(1, 15, 7)
print(np.dot(a,b))

155


In [12]:
m1 = np.random.randint(1, 11, (2,2))
m2 = np.random.randint(1, 11, (2,3))
print(np.dot(m1, m2))

[[104 104 144]
 [ 44  50  96]]


In [13]:
m1 = np.random.randint(1, 11, (3,3))
m1_inv = np.linalg.inv(m1)
print(m1_inv)

[[ 0.11764706 -0.14705882  0.17647059]
 [-0.05882353 -0.17647059  0.41176471]
 [-0.11764706  1.64705882 -2.17647059]]


In [14]:
m = np.random.random((4,4))
b = m.T
print(b)

[[0.01956842 0.2916953  0.88953545 0.64940133]
 [0.31624613 0.48341383 0.95434404 0.56039948]
 [0.25717059 0.72444809 0.61263416 0.89343257]
 [0.2500434  0.44143991 0.32585773 0.68376811]]


In [15]:
m1 = np.random.randint(1, 11, (3,4))
a = np.random.randint(1, 11, 4)
b = m1 * a
print(b)

[[24 60  8  8]
 [24  6  8 32]
 [30 60 28 16]]


In [16]:
m = np.random.random((2,3))
a = np.random.random(3)
b = m * a
print(b)

[[0.04259088 0.27736445 0.12552484]
 [0.33079754 0.18008226 0.04406041]]


In [19]:
m1 = np.random.randint(1, 11, (2,2))
m2 = np.random.randint(1, 11, (2,2))
print(m1 * m2)

[[24 60]
 [56 25]]


In [20]:
m1 = np.random.randint(1, 101, (5,5))
print(m1.sum())

1167


In [25]:
m1 = np.random.randint(1, 11, (4,4))
m2 = np.random.randint(1, 11, (4,4))
b = m1 - m2
print(b)

[[-9  2  3 -1]
 [-1 -3 -1  8]
 [-5  2  5 -1]
 [-1  2  2 -2]]


In [33]:
m = np.random.random((3,3))
print(m)
print(m.sum(axis=1))

[[0.86387001 0.31372486 0.47520162]
 [0.58761981 0.63873508 0.61216193]
 [0.50307471 0.42129885 0.08049075]]
[1.65279649 1.83851682 1.00486431]


In [37]:
m1 = np.random.randint(1,7,(3,4))
print(m1)
print(np.square(m1))

[[6 3 3 2]
 [4 3 5 6]
 [4 6 2 6]]
[[36  9  9  4]
 [16  9 25 36]
 [16 36  4 36]]


In [39]:
a = np.random.randint(1, 51, 4)
b = np.sqrt(a)
print(a)
print(b)

[10 16 47  8]
[3.16227766 4.         6.8556546  2.82842712]
